services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_network

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
    networks:
      - microservices_network


volumes:
  postgres_data:
    driver: local

networks:
  microservices_network:
    driver: bridge