services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices_network

  db:
    image: postgres:latest
    container_name: jobsearch-db
    environment:
      - POSTGRES_DB=jobsearch_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
    networks:
      - microservices_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices_network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices_network

  user-service:
    build:
      context: ./user-service
      dockerfile : Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices_network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices_network

volumes:
  postgres_data:

networks:
  microservices_network:
    driver: bridge